version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: telegrambotsmarketplace/marketplace_backend:test
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: telegrambotsmarketplace/marketplace_frontend:test
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: telegrambotsmarketplace/marketplace_nginx:test
    env_file: .env
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - static:/static
      - media:/app/media
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
