name: Develop deploy

on:
  workflow_run:
    workflows: ['Backend test', 'Push to docker hub']
    types:
      - completed
    branches:
      - 'develop'

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Application deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy docker-compose.yml via ssh to main server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          port: ${{ secrets.PORT_DEV }}
          username: ${{ secrets.USER_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          passphrase: ${{ secrets.SSH_PASSPHRASE_DEV }}
          source: "docker-compose-develop.yml"
          target: "infra"

      - name: Executing remote ssh commands to deploy to main server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          port: ${{ secrets.PORT_DEV }}
          username: ${{ secrets.USER_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          passphrase: ${{ secrets.SSH_PASSPHRASE_DEV }}
          script: |
            cd infra
            echo ${{ secrets.SSH_PASSPHRASE }} | sudo -S docker system prune -af
            echo ${{ secrets.SSH_PASSPHRASE }} | sudo -S docker compose pull
            echo ${{ secrets.SSH_PASSPHRASE }} | sudo -S docker compose down
            echo ${{ secrets.SSH_PASSPHRASE }} | sudo -S docker compose up -d
            echo ${{ secrets.SSH_PASSPHRASE }} | sudo -S docker compose exec backend python manage.py migrate
            echo ${{ secrets.SSH_PASSPHRASE }} | sudo -S docker compose exec backend python manage.py collectstatic
            echo ${{ secrets.SSH_PASSPHRASE }} | sudo -S docker compose exec backend cp -r /app/collected_static/. /backend_static/static/
